name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint (ubuntu x64)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Bench Build
        run: cargo bench --no-run

  test:
    name: test (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x64
            runner: ubuntu-24.04
          - name: linux-arm64
            runner: ubuntu-24.04-arm
          - name: windows-x64
            runner: windows-2025
          - name: windows-arm64
            runner: windows-11-arm
          - name: macos-intel
            runner: macos-15-intel
          - name: macos-arm64
            runner: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
      - name: Test with logging
        run: cargo test --features logging
